name: Build cppInterfaces

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download and Extract source
        run: |
          curl -L https://github.com/sysadminlab/cppInterfaces/releases/download/0.0.1/test-0.0.1-alpha.tar.gz -o source.tar.gz
          tar -xzf source.tar.gz
          cd test && rmdir test && mv * ..

      - name: Autoreconf
        run: autoreconf -i

      - name: Configure and Build
        run: |
          cd build
          ../configure
          make && make install
      - name: Run
        run: main
